name: Publish on tags

on:
  push:
    tags:
      - v*

env:
  CI: false
  VERBOSE: true
  IN_DOCKER: true

jobs:
  tests:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]    

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Tests
      run: pwsh ./tests.ps1
      working-directory: ./scripts

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Push package to nuget.org
        run: dotnet nuget push ./out/*.nupkg -k ${{ secrets.NUGET_DEPLOY_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate